# İlaç Veri Setleri Eşleştirme Projesi

Bu notebook, TİTCK ve ATC veri setlerinin temizlenerek bulanık eşleştirme (fuzzy matching) yöntemleriyle birleştirilmesi (record linkage) adımlarını içermektedir.

In [3]:
import pandas as pd
import numpy as np
from rapidfuzz import process, fuzz
import re

# Uyarıları kapatalım
import warnings
warnings.filterwarnings('ignore')

## 1. Veri Yükleme ve Keşifsel Veri Analizi (EDA)

In [4]:
# TİTCK verisini yükleme
try:
    df_titck = pd.read_csv('titck_liste_18.04.csv', sep=';')
except:
    df_titck = pd.read_csv('titck_liste_18.04.csv')

# ATC verisini yükleme
df_atc = pd.read_excel('ATC_14_04.xlsx')

print("TITCK Boyutu:", df_titck.shape)
print("ATC Boyutu:", df_atc.shape)

TITCK Boyutu: (15573, 4)
ATC Boyutu: (17907, 7)

In [5]:
df_titck.head(3)

,ID,Ilac_Adi,Etkin_Madde,Firma
0,0,% 0.4 LİDODEKS % 5 DEKSTROZ İÇİNDE İ.V. İNFÜZY...,LİDOKAİN HİDROKLORÜR,POLİFARMA İLAÇ SAN. VE TİC. A.Ş.
1,1,% 0.8 LİDODEKS % 5 DEKSTROZ İÇİNDE İ.V. İNFÜZY...,LİDOKAİN HİDROKLORÜR,POLİFARMA İLAÇ SAN. VE TİCARET A.Ş.
2,2,% 10 DEKSTROZ BIOSEL SUDAKI HIPERTONIK SOLÜSYONU,DEKSTROZ,OSEL ILAÇ SAN. VE TIC.A.Ş.

In [6]:
df_atc.head(3)

,İlaç Adı,Barkod,ATC Kodu,ATC Adı,Firma Adı,Reçete Türü,Durumu
0,HELICOBACTER TEST INFAI (C-URE) 75 MG 1 SISE,8699801967449,V04CX05,13C-urea,INFAI GMBH,Normal,Pasif
1,ZIAGEN 300 MG 60 FILM TABLET,8699522096107,J05AF06,abacavir,GLAXOSMİTHKLİNE İLAÇLARI SAN. VE TİC. A.Ş.,Normal,Aktif
2,ORENCIA 250 MG KON.PERFUZYONLUK COZ.ICIN TOZ I...,8699726266405,L04AA24,abatacept,BRISTOL-MYERS SQUIBB İLAÇLARI INC. İSTANBUL ŞU...,Normal,Aktif